main/urls.py
from django.urls import path
from main.views import show_main, create_relic, show_xml, show_json, show_json_by_id, show_xml_by_id
from main.views import register, login_user, logout_user, edit_Relic, delete_relic
from main.views import get_relic_json, add_relic_ajax, delete_relic_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-relic', create_relic, name='create_relic'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-relic/<int:id>', edit_Relic, name='edit_relic'),
    path('delete/<int:id>', delete_relic, name='delete_relic'),
    path('delete-ajax/<str:name>', delete_relic_ajax, name='delete_relic_ajax'),
    path('get-relic/', get_relic_json, name='get_relic_json'),
    path('create-relic-ajax/', add_relic_ajax, name='add_relic_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

relic_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Relic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    best_rarity = models.CharField(max_length=255)
    ideal_main_stat = models.CharField(max_length=255)
    ideal_variant_amount = models.IntegerField()

main/forms.py
from django.forms import ModelForm
from main.models import Relic

class RelicForm(ModelForm):
    class Meta:
        model = Relic
        fields = ["name", "amount", "description", "best_rarity", 
                  "ideal_main_stat", "ideal_variant_amount"]

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from main.forms import RelicForm
from django.urls import reverse
from main.models import Relic
import datetime
import json


# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    relics = Relic.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'PBP B',
        'relics' : relics,
        'last_login' : request.COOKIES['last_login']
    }

    return render(request, "main.html", context)

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return redirect('main:login')

def create_relic(request):
    form = RelicForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_relic.html", context)

def edit_Relic(request, id):
    relic = Relic.objects.get(pk = id)
    form = RelicForm(request.POST or None, instance=relic)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_relic.html", context)

def delete_relic(request, id):
    relic = Relic.objects.get(pk = id)
    relic.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def delete_relic_ajax(request, name):
    relic = get_object_or_404(Relic, name=name)
    relic.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_relic_json(request):
    relic_item = Relic.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', relic_item))

@csrf_exempt
def add_relic_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        best_rarity = request.POST.get("best_rarity")
        ideal_main_stat = request.POST.get("ideal_main_stat")
        ideal_variant_amount = request.POST.get("ideal_variant_amount")
        user = request.user

        new_relic = Relic(name=name, amount=amount, description=description, best_rarity=best_rarity, ideal_main_stat=ideal_main_stat, ideal_variant_amount=ideal_variant_amount, user=user)
        new_relic.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def show_xml(request):
    data = Relic.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Relic.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Relic.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Relic.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Relic.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_relic.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Relic</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_relic.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="login border border-light-subtle rounded-end p-3">
    <h1>Edit Relic</h1>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input class="btn btn-warning" type="submit" value="Edit Relic"/>
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class = "border border-light-subtle rounded-end p-3">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn btn-primary" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <h1>Inventory</h1>

    <h5>Name:</h5>
    <h4>{{name}}</h4>

    <h5>Class:</h5>
    <h4>{{class}}</h4>


<div class="card">
        <table class="table table-bordered table-striped" id="relic_table"> 
            <tr>
                <th>Name.</th>
                <th>amount</th>
                <th>Description</th>
                <th>Best Rarity</th>
                <th>Ideal Main Stat</th>
                <th>Ideal Variant Amount</th>
            </tr>

    {% for relic in relics %}
            <tr>
                <td>{{relic.name}}</td>
                <td>{{relic.amount}}</td>
                <td>{{relic.description}}</td>
                <td>{{relic.best_rarity}}</td>
                <td>{{relic.ideal_main_stat}}</td>
                <td>{{relic.ideal_variant_amount}}</td>
                <td>
                    <a href="{% url 'main:edit_relic' relic.pk %}">
                        <button class="btn btn-secondary">
                            Edit
                        </button>
                    </a>
                    <a href="{% url 'main:delete_relic' relic.pk %}">
                        <button class="btn btn-warning">
                            Delete
                        </button>
                    </a>
                </td>
            </tr>
    {% endfor %}
        </table>
</div>

<br />
<h5>Sesi terakhir login: {{ last_login }}</h5>

<a href="{% url 'main:create_relic' %}">
    <button class="btn btn-primary">
        Add New Relic
    </button>
</a>

<a href="{% url 'main:logout' %}">
    <button class="btn btn-warning">
        Logout
    </button>
</a>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add Product by AJAX
</button>




<div class="modal fade" tabindex="-1" id="deleteModal" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Relic</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <table class="table table-bordered table-striped" id="delete_table"></table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New relic</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="best_rarity" class="col-form-label">Best Rarity:</label>
                        <input type="number" class="form-control" id="best_rarity" name="best_rarity"></input>
                    </div>
                    <div class="mb-3">
                        <label for="ideal_main_stat" class="col-form-label">Ideal Main Stat:</label>
                        <input type="text" class="form-control" id="ideal_main_stat" name="ideal_main_stat"></input>
                    </div>
                    <div class="mb-3">
                        <label for="ideal_variant_amount" class="col-form-label">Ideal Variant Amount:</label>
                        <input type="number" class="form-control" id="ideal_variant_amount" name="ideal_variant_amount"></input>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Relic</button>
            </div>
        </div>
    </div>
</div>

<script>
    async function getRelics() {
        return fetch("{% url 'main:get_relic_json' %}").then((res) => res.json())
    }
    async function refreshRelics() {
        document.getElementById("relic_table").innerHTML = ""
        document.getElementById("delete_table").innerHTML = ""
        const relics = await getRelics()
        let htmlString2 = ``
        let htmlString = `
        <tr>
            <th>Name.</th>
            <th>amount</th>
            <th>Description</th>
            <th>Best Rarity</th>
            <th>Ideal Main Stat</th>
            <th>Ideal Variant Amount</th>
        </tr>`
        relics.forEach((item) => {
            htmlString += `\n<tr>
            <td>${item.fields.name}</td>
            <td>${item.fields.amount}</td>
            <td>${item.fields.description}</td>
            <td>${item.fields.best_rarity}</td>
            <td>${item.fields.ideal_main_stat}</td>
            <td>${item.fields.ideal_variant_amount}</td>
        </tr>` 
            htmlString2 += `
            <tr>
                <td>${item.fields.name}</td>
                <td>
                    <button class="btn btn-warning" data-bs-dismiss="modal" onclick="deleteRelic(this.innerText)">
                        ${item.fields.name}
                    </button>
                </td>
            </tr>`
        })

        document.getElementById("delete_table").innerHTML = htmlString2
        document.getElementById("relic_table").innerHTML = htmlString
    }

    function addRelic() {
        fetch("{% url 'main:add_relic_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshRelics)
        document.getElementById("form").reset()
        return false
    }

    function deleteRelic() {
        fetch("http://localhost:8000/delete-ajax/", {
            method : "DELETE",
        }).then(refreshRelics)
        return false
    }

    document.getElementById("button_add").onclick = addRelic
    refreshRelics()
    
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block content %}  

<div class = "login border border-light-subtle rounded-end p-3">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input class="btn btn-success" type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}